name: PR Merge

on:
  push:
    branches:
      - master

env:
  CI: true
  CARGO_TERM_COLOR: always
  CARGO_TAG_NAME: "GitHub Actions"
  CARGO_TAG_EMAIL: "github-actions@github.com"

permissions:
  contents: write

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cargo install
        uses: dimitrmo/cargo-verison-action@v1.0.25
        with:
          workspace: true
          skip-bump: true

      - name: Store binary
        uses: actions/upload-artifact@v4
        with:
          name: cargo-verison
          path: ~/.cargo/bin/cargo-verison
          retention-days: 1
          compression-level: 9

  Commit:
    runs-on: ubuntu-latest
    needs:
      - Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git setup
        run: |
          git config user.name "$CARGO_TAG_NAME"
          git config user.email "$CARGO_TAG_EMAIL"

      - name: Cargo Verison Setup
        uses: actions/download-artifact@v4
        with:
          name: cargo-verison
          path: ~/.cargo/bin/

      - name: Cargo Verison permissions
        run: chmod +x ~/.cargo/bin/cargo-verison

      - name: Cargo Verison
        id: verison
        uses: dimitrmo/cargo-verison-action@v1.0.25
        with:
          skip-install: true
          message: |
            Release %s

            [skip ci]

      - name: Extract git branch
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Git push
        run: |
          echo "Current branch $GIT_BRANCH"
          git push origin $GIT_BRANCH
          git push origin $GIT_BRANCH --tags

      - name: Cleanup
        uses: geekyeggo/delete-artifact@v5
        with:
          name: cargo-verison
          failOnError: false
