name: PR Merge

on:
  push:
    branches:
      - master

env:
  CI: true
  CARGO_TERM_COLOR: always
  CARGO_TAG_NAME: "GitHub Actions"
  CARGO_TAG_EMAIL: "github-actions@github.com"

permissions:
  contents: write

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cargo install
        uses: dimitrmo/cargo-verison-action@v1.0.26
        with:
          workspace: true
          skip-bump: true

      - name: Store binary
        uses: actions/upload-artifact@v4
        with:
          name: cargo-verison
          path: ~/.cargo/bin/cargo-verison
          retention-days: 1
          compression-level: 9

  Commit:
    runs-on: ubuntu-latest
    needs:
      - Setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git setup
        run: |
          git config user.name "$CARGO_TAG_NAME"
          git config user.email "$CARGO_TAG_EMAIL"

      - name: Cargo Verison Setup
        uses: actions/download-artifact@v4
        with:
          name: cargo-verison
          path: ~/.cargo/bin/

      - name: Cargo Verison permissions
        run: chmod +x ~/.cargo/bin/cargo-verison

      - name: Cargo Verison
        id: verison
        uses: dimitrmo/cargo-verison-action@v1.0.26
        with:
          workspace: false
          skip-install: true
          git-tag-version: false

      - name: Git Setup
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Setup wasm
        run: |
          cargo install wasm-pack

      - name: Build
        run: |
          make build

      - name: Extract git branch
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Git commit
        run: |
          echo "Current branch $GIT_BRANCH"
          
          git add .
          git commit -m "Release ${{ steps.verison.outputs.next_version }}
          
          [skip ci]
          "

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: NPM publish
        run: |
          make npm-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}

      - name: Git push
        run: |
          echo "Current branch $GIT_BRANCH"

          git tag ${{ steps.verison.outputs.next_version }}

          git push origin $GIT_BRANCH
          git push origin $GIT_BRANCH --tags

      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
          tag: ${{ steps.verison.outputs.next_version }}

      - name: Cleanup
        uses: geekyeggo/delete-artifact@v5
        with:
          name: cargo-verison
          failOnError: false
